### ISSUE TITLE
Kodi not auto syncing from/to Jellyfin anymore

### ISSUE THREAD

**Issue by EricCorleone** [jellyfin/jellyfin-plugin-kodisyncqueue#102]
The version of the Kodi Sync Queue I'm using is 13.0.0.0. Since yestersay, I found that Kodi (21.1) won't sync from Jellyfin (10.10) automatically anymore, and anything changed in Kodi won't be synced to Jellyfin either. I have to reset the Kodi database every time to see anything added to my Jellyfin library. Is there a solution?

**Comment by crobibero** [comment]
Please provide logs.

**Comment by EricCorleone** [comment]
I'm not sure why but everything works fine since yesterday. I don't know if it's because I did as the issue https://github.com/jellyfin/jellyfin-plugin-kodisyncqueue/issues/99#issuecomment-2442573611 said.
