### ISSUE TITLE
Plugin keeps disabling itself

### ISSUE THREAD

**Issue by cryptobank** [jellyfin/jellyfin-plugin-kodisyncqueue#15]
I have to keep going Dashboard -> Plugins -> Kodi Sync Queue -> Enable Plugin and tick Items To Track. 

Anyone with the same issue? Its really annoying.

**Comment by KaXaSA** [comment]
So... this is probably related to this Jellyfin issue:
[Unable to save settings #1881](https://github.com/jellyfin/jellyfin/issues/1881)
They are working on a fix ([#2008](https://github.com/jellyfin/jellyfin/pull/2008))

Right now you can try to:
- Close Jellyfin
- Access: `%localappdata%\jellyfin\plugins\configuration`
- Open the file: `Jellyfin.Plugin.KodiSyncQueue.xml`
- Copy, paste this:
 ```
<?xml version="1.0"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" />
	<txtRetDays>0</txtRetDays>
	<chkEnabled>true</chkEnabled>
	<tkMovies>true</tkMovies>
	<tkBoxSets>true</tkBoxSets>
	<tkTVShows>true</tkTVShows>
	<tkMusic>true</tkMusic>
	<tkMusicVideos>true</tkMusicVideos>
</PluginConfiguration>
```
- Change the settings to whatever you want and save it.

**Comment by phob** [comment]
#2008 was finished with 10.4.2

This is another bug I think with the plugin itself.
This only happens with docker(on linux).

To fix it you have to go into the container and edit the file yourself. Not very pleasant.

Also the title should be changed in Jellyfin.Plugin.KodiSyncQueue is not saving the settings.

**Comment by CoderMaurice** [comment]
I have the same problem,
What is the purpose of this plugin, the video I played on KODI, progress will not be synchronized to jellyfin, is this plugin used to handle it?

**Comment by jfml** [comment]
Same problem here, running Jellyfin 10.4.3 via Docker on a Synology, using Kodi addon 0.4(.1?) 😿

**Comment by FallenLeave91** [comment]
Same here. Thought it was related to the new version of the Kodi Sync Client 0.5.0 but i got the same error with 0.4.1.

**Comment by mcarlton00** [comment]
Is anybody still encountering this issue?  I believe it was mostly a UI quirk in the server where some existing settings wouldn't be loaded properly, but mine seems to be staying enabled now when I check on it recently.

@CoderMaurice this plugin is used for incremental syncs during Kodi's startup.  When you start Kodi it does the updates right away, that relies on this plugin.  Playback reporting and updates while Kodi is running are handled through different mechanisms

**Comment by jfml** [comment]
@mcarlton00 I've since switched to MPV-Shim, so I can't say, sorry.

**Comment by oddstr13** [comment]
This has been an issue server-side (in web iirc) a couple of times, so closing this now.
Comment here, reopen or create a new issue if you still encounter this issue.
