### ISSUE TITLE
Not returning updated Watched status

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-plugin-kodisyncqueue#16]
This appears to be the source for https://github.com/jellyfin/jellyfin-kodi/issues/50.

The plugin endpoint is returning a json payload of various changed items in the server since the last time Kodi was synced:
```
{
  "ItemsAdded":[],
  "ItemsRemoved":[],
  "ItemsUpdated":[],
  "UserDataChanged":[]
}
```

Added, Removed, and Updated all seem to be behaving properly, but I can't get UserDataChanged to populate.  It should be returning a list of items that have had their watched status changed (Watched, Unwatched, In Progress).

Example URL to load the endpoint:
`http://192.168.0.200:8096/Jellyfin.Plugin.KodiSyncQueue/$YOURUSERID/GetItems?LastUpdateDT=2019-12-12T02:58:43Z&filter=None`

**Comment by caspervk** [comment]
The regression likely occurred due to 845a6a4f1c979521f49384cc84b79f85bfed0815 or 54416a7a00a6f35708c5c5010d487fb94f887081.
