### ISSUE TITLE
Replace NanoApi

### ISSUE THREAD

**Issue by cvium** [jellyfin/jellyfin-plugin-kodisyncqueue#4]
This plugin uses https://github.com/jellyfin/jellyfin-plugin-kodisyncqueue/tree/master/Emby.Kodi.SyncQueue/NanoApi as a flat-file database, which is super weird.

It should be replaced with a proper DB, but it requires some coordination with the main repo as to how this should be done (interface via core or separate db etc.).

**Comment by JustAMan** [comment]
Especially as NanoApi seems to be an embedded 3rd party... which seems to be abandoned now.

**Comment by jfranki** [comment]
This should be closed as it was solved by #6.
