### ISSUE TITLE
Purpose of "Retention Days"?

### ISSUE THREAD

**Issue by wilcoxiv** [jellyfin/jellyfin-plugin-kodisyncqueue#56]
I couldn't find any documentation on this feature. What exactly is being retained in which database? I am guessing anything scanned after x days would need to be re-sync'd?

**Comment by jfranki** [comment]
I would like to know this too...

**Comment by Eddict** [comment]
from the [source](https://github.com/jellyfin/jellyfin-plugin-kodisyncqueue/blob/master/Jellyfin.Plugin.KodiSyncQueue/ScheduledTasks/RetentionTask.cs):
``` C#
        public string Description => "If retention days > 0 then this will remove the old data to keep information flowing quickly";
```
