### ISSUE TITLE
After docker upgrade to last version is Kodi Sync Queue7.0.0.0 Status: NotSupported

### ISSUE THREAD

**Issue by Termalator** [jellyfin/jellyfin-plugin-kodisyncqueue#57]
I upgraded my docker image from jellyfin/jellyfin:unstable and after that the Kodi Sync Queue plugin seems to be not supported, is there a workaround for that issue?

**Comment by NotExpectedYet** [comment]
Same, would be nice for 10.8.0 to be supported.

**Comment by Termalator** [comment]
You can run the jellyfin/jellyfin:20220212.44-unstable tag, this works but at some point after this tag this plugin is not supported anymore.

**Comment by NotExpectedYet** [comment]
> You can run the jellyfin/jellyfin:20220212.44-unstable tag, this works but at some point after this tag this plugin is not supported anymore.

I'm in no rush, and saves me messing with my custom docker build.

**Comment by MisterMcDuck** [comment]
Exception presumably causing the NotSupported status:

`[2022-03-10 00:31:05.639 +00:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/Kodi Sync Queue_7.0.0.0/Jellyfin.Plugin.KodiSyncQueue.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'ExecuteAsync' in type 'Jellyfin.Plugin.KodiSyncQueue.ScheduledTasks.RetentionTask' from assembly 'Jellyfin.Plugin.KodiSyncQueue, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Method 'ExecuteAsync' in type 'Jellyfin.Plugin.KodiSyncQueue.ScheduledTasks.RetentionTask' from assembly 'Jellyfin.Plugin.KodiSyncQueue, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

**Comment by crobibero** [comment]
I am aware. Plugins don't target unstable, so its expected to break. This will be fixed with the next release of Jellyfin.
