### ISSUE TITLE
New builds not showing in jellyfin unstable repository.

### ISSUE THREAD

**Issue by darkskiez** [jellyfin/jellyfin-plugin-kodisyncqueue#65]
I was looking for the latest nightly build to install from the unstable repo but it has nothing since the 7.0.0 release.

(There are plenty of nightlies for the 6 release, but it looks like they stopped getting built a year ago, and nothing after 7.)

(https://repo.jellyfin.org/releases/plugin/manifest-unstable.json)

**Comment by crobibero** [comment]
I don't believe the unstable repo is actually being used.
