### ISSUE TITLE
8.0.0 marked as NotSupported for Server 10.8.0

### ISSUE THREAD

**Issue by charredchar** [jellyfin/jellyfin-plugin-kodisyncqueue#67]
My install of Kodi recently stopped syncing to Jellyfin with an error popping up stating that Kodi Sync Queue was not installed on the server. I checked the plugins and found `Status: NotSupported`. I tried to remove and reinstall but the same issue persists.

**Comment by crobibero** [comment]
Which exact version of Jellyfin are you running?
I have the plugin working without issue on 10.8.0-beta2

**Comment by charredchar** [comment]
I believe it is one of the alphas but the interface is not explicitly telling me. It was awhile ago though and installed as the Windows Service. I wouldn't mine updating to Beta2 as long as it won't break anything...

**Comment by charredchar** [comment]
I actually managed to find that I was running Alpha3. Figured I'd try Beta2 ... and it broke the server. ☹️

**Comment by chris3687994** [comment]
I have the same problem.The plugin witch ver 8.0.0.0 also not work on my jellyfin server.It shows "Not Support".My jellyfin server version is 10.8 and run in docker container. Jellyfin image is 
"nyanmisaka/jellyfin:latest".

**Comment by charredchar** [comment]
Took me a little time to report back because Beta2 once again broke things and I needed to rebuild from scratch... Getting tired of doing this.
I can, at least, confirm that the issue went away with Beta2 from Alpha3. But I would really like to avoid this again as I don't like to change my server if it is working, I don't have auto-updates on anything. I didn't update Jellyfin, Kodi or Sync Queue but this error randomly appeared. Do we know what would cause such a thing and a way to stop it from happening again?

**Comment by mcarlton00** [comment]
I feel like this has to be stated for clarity.  If you want stability, you shouldn't be running alphas or betas.  They're meant for users who want to live on the edge and help find bugs.  While we do our best to make sure things are stable before they're released, there will always be bugs that the team misses.  You didn't accidentally or automatically get put onto the alpha track for the server, you had to make manual changes for that to happen.

The other part of this is that plugins will update automatically unless told otherwise.  95% of the time this is a nonissue, it only really comes into play during the alphas/betas because they're technically the same version number and there's limitations of how far it can get scoped.

**Comment by charredchar** [comment]
> I feel like this has to be stated for clarity. If you want stability, you shouldn't be running alphas or betas. They're meant for users who want to live on the edge and help find bugs. While we do our best to make sure things are stable before they're released, there will always be bugs that the team misses. You didn't accidentally or automatically get put onto the alpha track for the server, you had to make manual changes for that to happen.

I 100% agree with this, but similar to Sync Queue I had another plugin that I required (LADP) which needed Server 10.8.0 to function which forced me on to the Alpha3.

> The other part of this is that plugins will update automatically unless told otherwise. 95% of the time this is a nonissue, it only really comes into play during the alphas/betas because they're technically the same version number and there's limitations of how far it can get scoped.

While true, that 5% has also bit me in the past which is why I turn off auto-update. When a server functions, unless I need a specific feature of a new version or to fix a security issue, there is no reason for me to update. But from the sound of this, Sync Queue 8.0.0 was updated with this bug that stopped it from working on Alpha3?

Double checking my settings, I think auto-update for plugins was still enabled from when I installed Alpha3. I can't remember if I missed this or not, but since I had to install Beta2 it seems it enabled auto-updates again. I tried 7.0.0 before installing Beta2 but that did not work either, but if I recall 7.0.0 doesn't work on Server 10.8.0?

**Comment by crobibero** [comment]
Assuming this is no longer an issue.
