### ISSUE TITLE
Synchronization doesn't work

### ISSUE THREAD

**Issue by definitio** [jellyfin/jellyfin-plugin-kodisyncqueue#9]
Emby for Kodi 4.0.5 shows error on start if Kodi companion enabled in plugin's settings.
There are errors in Jellyfin log:
```
[ERR] Could not find handler for /emby/Emby.Kodi.SyncQueue/<userId>/GetItems
```

**Comment by JustAMan** [comment]
Can you try using our Jellyfin for Kodi instead? https://jellyfin.readthedocs.io/en/latest/user-docs/apps/#installing

I don't think we will be trying to support both.

**Comment by definitio** [comment]
It works. Thanks.
