### ISSUE TITLE
Jellyfin 10.10 - Method not found: 'Void MediaBrowser.Model.Dto.UserItemDataDto.set_ItemId(System.String)'

### ISSUE THREAD

**Issue by pimw1** [jellyfin/jellyfin-plugin-kodisyncqueue#96]
Hi, after installing Jellyfin 10.10.0 (build 2024092305) and switching over to the unstable plugin repo (https://repo.jellyfin.org/files/plugin-unstable/manifest.json), i am seeing the following error when playing a movie in Google chrome:

https://privatebin.net/?295b62974c84b1dd#Gqx6q744Ux7aYh1RzBe5Qmg8vM4CtspSTwy4tihsY3Qm

The movie itself is playing fine, but i see the error showing in the logs. I'm using version 11.0.0.0 of the Kodi Sync Queue.

I'm not sure if this error is related to the upgrade to Jellyfin 10.10 (i'm scrutinizing logs since the upgrade from 10.9).

**Comment by crobibero** [comment]
The plugins have not yet been updated to be compatible with 10.10, but thank you for letting us know.

**Comment by razor2611** [comment]
Same thing here, any ETA on when this will be updated? 
Thank you.

**Comment by crobibero** [comment]
About 3 days ago?
https://github.com/jellyfin/jellyfin-plugin-kodisyncqueue/releases/tag/v12

Note that you may need to reset the plugin databases https://github.com/jellyfin/jellyfin-plugin-kodisyncqueue/issues/99
